---
output:
  pdf_document: default
  html_document: default
---
**Introduction**

Anthozoans are a class within the Cnidarians that includes corals, anemones and their relatives. In contrast to insect immune responses, very little is known about the immune response of this key group of invertebrates. Initial characterizations of immune related genes in cnidarians using genome and EST scans indicated that they possess the Toll/TLR pathway, complement C3, membrane attack complex/perforin domains, and other components of innate immunity once thought to have evolved much later [^Miller2007]. However, very little data existed indicating whether or not these immune pathways were actually used in cnidarians to mount a response against pathogens. A number of groups have since used RNA-seq to produce some of the first profiles of anthozoan innate immunity. Weiss et al. (2013) studied the response of *Acropora millepora* to the bacterial cell wall derivative muramyl dipeptide (MDP), finding up-regulation of GTPases of immunity associated proteins (GiMAPs) [^Weiss2013]. GiMAPS were formerly primarily associated with vertebrates and plants [^Liu2008] [^Wang2009]. Vidal-Dupiol et al. (2014) compared the transcriptomic responses of *Pocillopora damicornis* to thermal stress and *Vibrio coralliilyticus* Infection and found overall down-regulation of immune processes in response to thermal stress combined with thermally-induced virulence factors in *V. coralliilyticus.* Affected pathways included Toll-like, complement, prophenoloxidase, and the leukotriene cascade. Libro et al. (2013) compared the immune response of healthy and diseased corals using RNA-seq, finding up-regulation of C-type lectins, ROS production, arachidonic acid metabolism, and allene oxide production in diseased corals [^Libro2013]. Up-regulation of C-type lectins and ROS production are hallmarks of phagocytosis, and the metabolism of arachidonic acid via the allene oxide pathway has been linked to eicosanoid synthesis in wounded corals [^Lõhelaid]. Interestingly, they did not identify strong up-regulation of genes associated with the classic innate immune pathways such as Toll-like receptor pathway or Prophenoloxidase pathway.

Reef-building corals and other anthozoans like *Aiptasia* are well known for their symbiotic relationship with the dinoflagellate *Symbiodinium* (also called zooxanthellae or “zoox”). The symbionts live in vacuoles inside the endodermis of the coral and give the host up to 95% of its energy as translocated polysaccharides. Symbiosis requires clear communication between the host and symbiont. During the establishment of symbiosis, the host must be able to recognize symbionts, engulf them in phagosomes, and shield these phagosomes from destruction [^Davy2012]. This suggests a clear link between symbioses and immunity wherein symbionts evade the immune response. Arrest of phagosomal maturation by Rab GTPases [^Davy2012] and suppression of immune responses by transforming growth factor beta (TGFB) have been identified as potential mechanisms by which symbionts are shielded from destruction by the immune system [^Detournay2012]. Once symbiosis is established, the host must regulate the growth of the symbionts and eject dead or dying symbionts [^Davy2012]. Regulation of nutrients has been identified as one mechanism by which the host can prevent overgrowth of the dinoflagellates [^Davy2012]. For corals and other symbiotic anemones, we know very little about how the relationship is maintained. Instead, we know a great deal about the breakdown in the symbiosis – known as bleaching – when the symbionts to be degraded or expelled by the coral host under stressful conditions like increased temperature.

